[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "rust"
file-types = ["rs","toml"]
auto-format = false
indent = {tab-width = 8, unit = "\t"}
formatter = {command = "rustfmt", args = []}
language-servers = ["rust-analyzer"]
